package com.dapm.security_service.models.enums;

public enum ProjectPermAction {

    CONFIGURE_PIPELINE,
    START_PIPELINE,
    ACCESS_REQUEST_PE,
    ASSIGN_USER_PROJECT_ROLE,


    INSTANTIATE_PE,
    INSTANTIATE_PIPELINE,

    READ_PIPELINE,
    READ_PIPELINES,
    READ_PE,
    READ_PES,

    UPDATE_PROJECT,

    DELETE_PIPELINE,
    DELETE_PE,
    CREATE_PIPELINE
}

