version: "3.8"

services:
  postgres_orga:
    image: postgres:14
    container_name: dapm_postgres_orga
    environment:
      POSTGRES_USER: orga_user
      POSTGRES_PASSWORD: orga_pass
      POSTGRES_DB: orga_db
    ports:
      - "5433:5432"
    volumes:
      - orga_data:/var/lib/postgresql/data
    networks:
      - dapm_network

  postgres_orgb:
    image: postgres:14
    container_name: dapm_postgres_orgb
    environment:
      POSTGRES_USER: orgb_user
      POSTGRES_PASSWORD: orgb_pass
      POSTGRES_DB: orgb_db
    ports:
      - "5434:5432"
    volumes:
      - orgb_data:/var/lib/postgresql/data
    networks:
      - dapm_network

  dapm_orga:
    build: .
    container_name: orga
    environment:
      - dapm.defaultOrgName=OrgA
      - SPRING_DATASOURCE_URL=jdbc:postgresql://dapm_postgres_orga:5432/orga_db
      - SPRING_DATASOURCE_USERNAME=orga_user
      - SPRING_DATASOURCE_PASSWORD=orga_pass
      - spring.jpa.hibernate.ddl-auto=update
      - spring.jpa.show-sql=true
    ports:
      - "8081:8080"  # Mapping internal port 8080 to external port 8081
    depends_on:
      - postgres_orga
    networks:
      - dapm_network

  dapm_orgb:
    build: .
    container_name: orgb
    environment:
      - dapm.defaultOrgName=OrgB
      - SPRING_DATASOURCE_URL=jdbc:postgresql://dapm_postgres_orgb:5432/orgb_db
      - SPRING_DATASOURCE_USERNAME=orgb_user
      - SPRING_DATASOURCE_PASSWORD=orgb_pass
      - spring.jpa.hibernate.ddl-auto=update
      - spring.jpa.show-sql=true
    ports:
      - "8082:8080"  # Mapping internal port 8080 to external port 8082
    depends_on:
      - postgres_orgb
    networks:
      - dapm_network

volumes:
  orga_data:
  orgb_data:

networks:
  dapm_network:
    driver: bridge